services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - .data:/mnt/data
      - ./src:/app/src
    depends_on:
      - worker
      - caddy
  worker:
    build: .
    command: cervo-worker
    restart: unless-stopped
    volumes:
      - .data:/mnt/data
      - ./src:/app/src
  caddy:
    image: caddy:latest
    command: caddy run --config /mnt/data/Caddyfile --adapter caddyfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - .data:/mnt/data
