"""Static sites: what one is, and how one comes to exist.

``_dao`` is private to this package: its leading underscore says so, and
ruff's TID251 rule enforces it. Callers go through the service.
"""

from cervo.website.service import (
    ACTIVATE_KIND,
    CONFIGURE_KIND,
    DELETE_FILE_CHAIN,
    DELETE_FILE_KIND,
    DELETE_KIND,
    DEPLOY_CHAIN,
    FILE_CHAIN,
    MAX_FILE_BYTES,
    PROVISION_KIND,
    VALIDATE_FILE_KIND,
    WRITE_FILE_KIND,
    WebsiteError,
    all_sites,
    check_content,
    create,
    create_tables,
    delete,
    exists,
    file_deletion_state,
    file_state,
    file_target,
    for_user,
    get,
    live,
    submit_file,
    submit_file_deletion,
)
from cervo.website.types import (
    FileDeletion,
    FilePath,
    FileStatus,
    FileWrite,
    Slug,
    Website,
    WebsiteStatus,
)

__all__ = [
    "ACTIVATE_KIND",
    "CONFIGURE_KIND",
    "DELETE_FILE_CHAIN",
    "DELETE_FILE_KIND",
    "DELETE_KIND",
    "DEPLOY_CHAIN",
    "FILE_CHAIN",
    "MAX_FILE_BYTES",
    "PROVISION_KIND",
    "VALIDATE_FILE_KIND",
    "WRITE_FILE_KIND",
    "FileDeletion",
    "FilePath",
    "FileStatus",
    "FileWrite",
    "Slug",
    "Website",
    "WebsiteError",
    "WebsiteStatus",
    "all_sites",
    "check_content",
    "create",
    "create_tables",
    "delete",
    "exists",
    "file_deletion_state",
    "file_state",
    "file_target",
    "for_user",
    "get",
    "live",
    "submit_file",
    "submit_file_deletion",
]
